### ISSUE TITLE
Code Review on commit "Deleting mask components when selecting new mask"

### ISSUE THREAD

**Issue by TomDotScott** [TU-Beta-Arcade-Team-2/Bwoom#2]
First things first, I'm getting 
`NullReferenceException: Object reference not set to an instance of an object
Controller.MaskInputs () (at Assets/Scripts/Player/Controller.cs:124)
Controller.Update () (at Assets/Scripts/Player/Controller.cs:83)
`
If any of the mask selection buttons are pressed! 

The MaskBase looks like a good start so far! It should be marked as abstract since we are never going to have a mask instance on its own, we want it to exist through its children.

My main change in the base class is in this function here:
```Csharp
public void MaskChange(int maskNo) // Create an enum called eMaskType, and have m_maskType be a new member 
{
    switch(maskNo) // Do a switch on m_maskType 
    {
        case 0: // Which means that these cases become a lot more easy to read too!
            if (!gameObject.GetComponent<WarMask>())
            {
                RemoveMasks();
                gameObject.AddComponent(typeof(WarMask));
            }
            break;
       case 1:
            if (!gameObject.GetComponent<NatureMask>())
            {
                RemoveMasks();
                gameObject.AddComponent(typeof(NatureMask));
            }
            break;
    }
}
```
Also, since `AddComponent`, `GetComponent` and `RemoveComponent` are super expensive functions, it might be better to enable and disable them using `.enabled` rather than creating new ones every time we swap masks. 

In terms of the mask child classes, I have one complaint... **ABSOLUTE PATHS**! Eek
```Chsarp
[SerializeField] private string pathName = "Sprites/TempSprites/ExampleMask2@4x";
```
The reasons this is bad are endless... If the artists change a file name, the code breaks. If the designers change some file locations, the code breaks. If we make a typo, the code breaks! 

It would be better to have a `protected SpriteRenderer` component on the Base Class and then override it in the children. 

Other than that! Good start Islam! Excited to get these mechanics up and running properly!

**Comment by Islamjdallali** [comment]
I have been implementing the feedback (thanks for that). There is one thing I want to talk about tho, and that is making the mask class an abstract class, if I am going to make the mask class abstract then surely the controller class will have to move the MaskChange function to the controller class and I kinda don't want to do that, I don't want the controller class to have to manage the mask changes if it is possible.
